import Vue from 'vue';
import { Button,List,Cell,Tabbar,Tag,TabbarItem,Empty,Search,Icon,Swipe, SwipeItem,CellGroup,Field,Grid, GridItem,Image,DropdownMenu, DropdownItem} from 'vant';

Vue.use(Button);
Vue.use(Tabbar);
Vue.use(TabbarItem);
Vue.use(Search);
Vue.use(Icon);
Vue.use(Swipe);
Vue.use(SwipeItem);
Vue.use(CellGroup);
Vue.use(Field);
Vue.use(Tag);
Vue.use(Grid);
Vue.use(GridItem);
Vue.use(Image);
Vue.use(DropdownMenu);
Vue.use(DropdownItem);
Vue.use(Empty);
Vue.use(List);
Vue.use(Cell);